# Revision of PyTorch basics

In [1]:
#!jt -l
#!jt -t [theme name]

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
print (torch.__version__) 
# Version 2 was released yesterday. Also see https://github.com/rasbt/pytorch-fabric-demo
# on how to speed up some computations. 

2.0.0


In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data.shape
tensor = x_data

In [5]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


From a numpy array

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.9483, 0.0286],
        [0.0818, 0.8413]]) 



In [8]:
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n") # Same shape

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [10]:
# We move our tensor to the GPU if available

if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

# Indexing 

In [11]:
tensor = torch.rand(4, 4)
#tensor[:,1] = 0 # Set column 1 to 0.
print(tensor)

tensor([[0.7880, 0.9490, 0.0621, 0.0455],
        [0.3252, 0.4195, 0.1215, 0.2743],
        [0.0587, 0.0120, 0.1959, 0.9949],
        [0.7310, 0.8803, 0.9587, 0.4675]])


In [12]:
print (tensor[:])

tensor([[0.7880, 0.9490, 0.0621, 0.0455],
        [0.3252, 0.4195, 0.1215, 0.2743],
        [0.0587, 0.0120, 0.1959, 0.9949],
        [0.7310, 0.8803, 0.9587, 0.4675]])


In [13]:
print (tensor[1:3])

tensor([[0.3252, 0.4195, 0.1215, 0.2743],
        [0.0587, 0.0120, 0.1959, 0.9949]])


In [14]:
print (tensor[:2])

tensor([[0.7880, 0.9490, 0.0621, 0.0455],
        [0.3252, 0.4195, 0.1215, 0.2743]])


In [15]:
print (tensor[:-1])

tensor([[0.7880, 0.9490, 0.0621, 0.0455],
        [0.3252, 0.4195, 0.1215, 0.2743],
        [0.0587, 0.0120, 0.1959, 0.9949]])


In [16]:
print (tensor[1:4:2]) # Only 1 and 3rd rows 

tensor([[0.3252, 0.4195, 0.1215, 0.2743],
        [0.7310, 0.8803, 0.9587, 0.4675]])


In [17]:
print (tensor[1:4:2, :2]) # # Only 1 and 3rd rows and first two columns 

tensor([[0.3252, 0.4195],
        [0.7310, 0.8803]])


In [18]:
t1 = torch.cat([tensor, tensor], dim=1)
print (t1)

tensor([[0.7880, 0.9490, 0.0621, 0.0455, 0.7880, 0.9490, 0.0621, 0.0455],
        [0.3252, 0.4195, 0.1215, 0.2743, 0.3252, 0.4195, 0.1215, 0.2743],
        [0.0587, 0.0120, 0.1959, 0.9949, 0.0587, 0.0120, 0.1959, 0.9949],
        [0.7310, 0.8803, 0.9587, 0.4675, 0.7310, 0.8803, 0.9587, 0.4675]])


In [19]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

tensor.mul(tensor) 
 tensor([[6.2100e-01, 9.0058e-01, 3.8571e-03, 2.0702e-03],
        [1.0577e-01, 1.7596e-01, 1.4774e-02, 7.5252e-02],
        [3.4401e-03, 1.4292e-04, 3.8377e-02, 9.8982e-01],
        [5.3434e-01, 7.7499e-01, 9.1913e-01, 2.1860e-01]]) 



In [20]:
print (tensor**2)

tensor([[6.2100e-01, 9.0058e-01, 3.8571e-03, 2.0702e-03],
        [1.0577e-01, 1.7596e-01, 1.4774e-02, 7.5252e-02],
        [3.4401e-03, 1.4292e-04, 3.8377e-02, 9.8982e-01],
        [5.3434e-01, 7.7499e-01, 9.1913e-01, 2.1860e-01]])


In [21]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[1.5275, 0.6744, 0.1150, 1.4923],
        [0.6744, 0.3718, 0.3208, 0.8518],
        [0.1150, 0.3208, 1.0318, 0.7064],
        [1.4923, 0.8518, 0.7064, 2.4471]]) 

tensor @ tensor.T 
 tensor([[1.5275, 0.6744, 0.1150, 1.4923],
        [0.6744, 0.3718, 0.3208, 0.8518],
        [0.1150, 0.3208, 1.0318, 0.7064],
        [1.4923, 0.8518, 0.7064, 2.4471]])


In [22]:
tensor.add_(1)
print(tensor)

tensor([[1.7880, 1.9490, 1.0621, 1.0455],
        [1.3252, 1.4195, 1.1215, 1.2743],
        [1.0587, 1.0120, 1.1959, 1.9949],
        [1.7310, 1.8803, 1.9587, 1.4675]])


In [23]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
scalar.ndim

0

In [25]:
scalar.item()

7

In [26]:
torch.max(tensor), torch.min(tensor), torch.mean(tensor.type(torch.float32)), torch.sum(tensor)

(tensor(1.9949), tensor(1.0120), tensor(1.4553), tensor(23.2842))

In [27]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [28]:
# Create a tensor by reshaping list 

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Check http://www.learnpytorch.io/00_pytorch_fundamentals/ for more related stuff 

In [29]:
tensor_of_ones = torch.ones(3, 3)
identity_tensor = torch.eye(3)
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)
element_multiplication = torch.mul(tensor_of_ones, identity_tensor)
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [30]:
random_ten = torch.rand(3, 3)
print (random_ten)

tensor([[0.7080, 0.2323, 0.6620],
        [0.1443, 0.0488, 0.7738],
        [0.9732, 0.3495, 0.2911]])


In [31]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


In [32]:
# Multiply tensors x and y
x = torch.rand(100, 100)
y = torch.rand(100, 100)
q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradient
mean_f.backward()

In [33]:
# Initialize the weights of the neural network
input_layer = torch.rand(1, 784)
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([[19722.3086, 20590.9883, 20290.3203, 19154.3086, 20124.9375, 19716.2461,
         20408.6484, 21740.9844, 19879.5684, 20918.3730]])


In [34]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

NameError: name 'nn' is not defined

In [ ]:
# import torch library
import torch

# create tensors with requires_grad = true
x = torch.tensor(3.0, requires_grad = True)
y = torch.tensor(4.0, requires_grad = True)

# print the tensors
print("x:", x)
print("y:", y)

# define a function z of above created tensors
z = x**y
print("z:", z)

# call backward function for z to compute the gradients
z.backward()

# Access and print the gradients w.r.t x, and y
dx = x.grad
dy = y.grad
print("x.grad :", dx)
print("y.grad :", dy)

x: tensor(3., requires_grad=True)
y: tensor(4., requires_grad=True)
z: tensor(81., grad_fn=<PowBackward1>)
x.grad : tensor(108.)
y.grad : tensor(88.9876)


We will now compute some simple derivatives. Let's assume 

$a = 1 \qquad b = 2 \qquad  c = a^2 b  \qquad  d = \Big(a + \frac{\partial c}{\partial a}\Big) b$

and we want $\frac{\partial d}{\partial a}$ which for b=2 is 10. 

In [ ]:
import torch

a = torch.tensor(1., requires_grad=True)
b = torch.tensor(2.)
c = a * a * b
dc_da = torch.autograd.grad(c, a, create_graph=True)[0]
#dc_da = torch.autograd.grad(c, a)[0]

d = (a + dc_da) * b
dd_da = torch.autograd.grad(d, a)[0]

print('c: {}, dc_da: {}, d: {}, dd_da: {}'.format(c, dc_da, d, dd_da))

c: 2.0, dc_da: 4.0, d: 10.0, dd_da: 10.0
