# Revision of PyTorch basics

In [1]:
#!jt -l
#!jt -t [theme name]

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [2]:
import torch
import numpy as np

In [44]:
print (torch.__version__) 
# Version 2 was released yesterday. Also see https://github.com/rasbt/pytorch-fabric-demo
# on how to speed up some computations. 

2.1.0.dev20230316


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data.shape
tensor = x_data

In [4]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


From a numpy array

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.2779, 0.3346],
        [0.1300, 0.4353]]) 



In [7]:
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n") # Same shape

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [9]:
# We move our tensor to the GPU if available

if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

# Indexing 

In [10]:
tensor = torch.rand(4, 4)
#tensor[:,1] = 0 # Set column 1 to 0.
print(tensor)

tensor([[0.0297, 0.3921, 0.7091, 0.3205],
        [0.5766, 0.2417, 0.6700, 0.4375],
        [0.5547, 0.3944, 0.9381, 0.0025],
        [0.5324, 0.7091, 0.6851, 0.6813]])


In [11]:
print (tensor[:])

tensor([[0.0297, 0.3921, 0.7091, 0.3205],
        [0.5766, 0.2417, 0.6700, 0.4375],
        [0.5547, 0.3944, 0.9381, 0.0025],
        [0.5324, 0.7091, 0.6851, 0.6813]])


In [12]:
print (tensor[1:3])

tensor([[0.5766, 0.2417, 0.6700, 0.4375],
        [0.5547, 0.3944, 0.9381, 0.0025]])


In [13]:
print (tensor[:2])

tensor([[0.0297, 0.3921, 0.7091, 0.3205],
        [0.5766, 0.2417, 0.6700, 0.4375]])


In [14]:
print (tensor[:-1])

tensor([[0.0297, 0.3921, 0.7091, 0.3205],
        [0.5766, 0.2417, 0.6700, 0.4375],
        [0.5547, 0.3944, 0.9381, 0.0025]])


In [15]:
print (tensor[1:4:2]) # Only 1 and 3rd rows 

tensor([[0.5766, 0.2417, 0.6700, 0.4375],
        [0.5324, 0.7091, 0.6851, 0.6813]])


In [16]:
print (tensor[1:4:2, :2]) # # Only 1 and 3rd rows and first two columns 

tensor([[0.5766, 0.2417],
        [0.5324, 0.7091]])


In [17]:
t1 = torch.cat([tensor, tensor], dim=1)
print (t1)

tensor([[0.0297, 0.3921, 0.7091, 0.3205, 0.0297, 0.3921, 0.7091, 0.3205],
        [0.5766, 0.2417, 0.6700, 0.4375, 0.5766, 0.2417, 0.6700, 0.4375],
        [0.5547, 0.3944, 0.9381, 0.0025, 0.5547, 0.3944, 0.9381, 0.0025],
        [0.5324, 0.7091, 0.6851, 0.6813, 0.5324, 0.7091, 0.6851, 0.6813]])


In [18]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

tensor.mul(tensor) 
 tensor([[8.8288e-04, 1.5376e-01, 5.0285e-01, 1.0274e-01],
        [3.3249e-01, 5.8426e-02, 4.4883e-01, 1.9139e-01],
        [3.0771e-01, 1.5556e-01, 8.8001e-01, 6.2521e-06],
        [2.8350e-01, 5.0287e-01, 4.6938e-01, 4.6418e-01]]) 



In [19]:
print (tensor**2)

tensor([[8.8288e-04, 1.5376e-01, 5.0285e-01, 1.0274e-01],
        [3.3249e-01, 5.8426e-02, 4.4883e-01, 1.9139e-01],
        [3.0771e-01, 1.5556e-01, 8.8001e-01, 6.2521e-06],
        [2.8350e-01, 5.0287e-01, 4.6938e-01, 4.6418e-01]])


In [20]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[0.7602, 0.7272, 0.8372, 0.9981],
        [0.7272, 1.0311, 1.0448, 1.2355],
        [0.8372, 1.0448, 1.3433, 1.2195],
        [0.9981, 1.2355, 1.2195, 1.7199]]) 

tensor @ tensor.T 
 tensor([[0.7602, 0.7272, 0.8372, 0.9981],
        [0.7272, 1.0311, 1.0448, 1.2355],
        [0.8372, 1.0448, 1.3433, 1.2195],
        [0.9981, 1.2355, 1.2195, 1.7199]])


In [21]:
tensor.add_(1)
print(tensor)

tensor([[1.0297, 1.3921, 1.7091, 1.3205],
        [1.5766, 1.2417, 1.6700, 1.4375],
        [1.5547, 1.3944, 1.9381, 1.0025],
        [1.5324, 1.7091, 1.6851, 1.6813]])


In [22]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [23]:
scalar.ndim

0

In [24]:
scalar.item()

7

In [25]:
torch.max(tensor), torch.min(tensor), torch.mean(tensor.type(torch.float32)), torch.sum(tensor)

(tensor(1.9381), tensor(1.0025), tensor(1.4922), tensor(23.8750))

In [26]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [27]:
# Create a tensor by reshaping list 

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Check http://www.learnpytorch.io/00_pytorch_fundamentals/ for more related stuff 

In [28]:
tensor_of_ones = torch.ones(3, 3)
identity_tensor = torch.eye(3)
matrices_multiplied = torch.matmul(tensor_of_ones, identity_tensor)
print(matrices_multiplied)
element_multiplication = torch.mul(tensor_of_ones, identity_tensor)
print(element_multiplication)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [29]:
random_ten = torch.rand(3, 3)
print (random_ten)

tensor([[0.7540, 0.6371, 0.7954],
        [0.4313, 0.6242, 0.1619],
        [0.7664, 0.0843, 0.4115]])


In [30]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., requires_grad=True)
y = torch.tensor(-3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

# Set q to sum of x and y, set f to product of q with z
q = x + y
f = q * z

# Compute the derivatives
f.backward()

# Print the gradients
print("Gradient of x is: " + str(x.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of z is: " + str(z.grad))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


In [36]:
# Multiply tensors x and y
x = torch.rand(100, 100)
y = torch.rand(100, 100)
q = torch.matmul(x, y)

# Elementwise multiply tensors z with q
f = z * q

mean_f = torch.mean(f)

# Calculate the gradient
mean_f.backward()

None


In [41]:
# Initialize the weights of the neural network
input_layer = torch.rand(1, 784)
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([[19897.5352, 18113.7676, 19080.8125, 18622.8320, 19020.5586, 20282.0195,
         20888.8027, 19176.2344, 19186.8438, 21343.5449]])


In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Instantiate all 2 linear layers  
        self.fc1 = nn.Linear(784, 200)
        self.fc2 = nn.Linear(200, 10)

    def forward(self, x):
        # Use the instantiated layers and return x
        x = self.fc1(x)
        x = self.fc2(x)
        return x

In [45]:
# import torch library
import torch

# create tensors with requires_grad = true
x = torch.tensor(3.0, requires_grad = True)
y = torch.tensor(4.0, requires_grad = True)

# print the tensors
print("x:", x)
print("y:", y)

# define a function z of above created tensors
z = x**y
print("z:", z)

# call backward function for z to compute the gradients
z.backward()

# Access and print the gradients w.r.t x, and y
dx = x.grad
dy = y.grad
print("x.grad :", dx)
print("y.grad :", dy)

x: tensor(3., requires_grad=True)
y: tensor(4., requires_grad=True)
z: tensor(81., grad_fn=<PowBackward1>)
x.grad : tensor(108.)
y.grad : tensor(88.9876)


We will now compute some simple derivatives. Let's assume 

$a = 1 \qquad b = 2 \qquad  c = a^2 b  \qquad  d = \Big(a + \frac{\partial c}{\partial a}\Big) b$

and we want $\frac{\partial d}{\partial a}$ which for b=2 is 10. 

In [48]:
import torch

a = torch.tensor(1., requires_grad=True)
b = torch.tensor(2.)
c = a * a * b
dc_da = torch.autograd.grad(c, a, create_graph=True)[0]
#dc_da = torch.autograd.grad(c, a)[0]

d = (a + dc_da) * b
dd_da = torch.autograd.grad(d, a)[0]

print('c: {}, dc_da: {}, d: {}, dd_da: {}'.format(c, dc_da, d, dd_da))

c: 2.0, dc_da: 4.0, d: 10.0, dd_da: 10.0
