# Revision of PyTorch basics

In [2]:
import torch
import numpy as np

In [11]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data.shape
tensor = x_data

In [12]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


From a numpy array

In [13]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [14]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8064, 0.6294],
        [0.7274, 0.5060]]) 



In [15]:
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n") # Same shape

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [16]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [18]:
# We move our tensor to the GPU if available

if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

# Indexing 

In [27]:
tensor = torch.rand(4, 4)
#tensor[:,1] = 0 # Set column 1 to 0.
print(tensor)

tensor([[0.6647, 0.7188, 0.3548, 0.8124],
        [0.2400, 0.3001, 0.4728, 0.2524],
        [0.5713, 0.0936, 0.3176, 0.9246],
        [0.1478, 0.0356, 0.3905, 0.8292]])


In [28]:
print (tensor[:])

tensor([[0.6647, 0.7188, 0.3548, 0.8124],
        [0.2400, 0.3001, 0.4728, 0.2524],
        [0.5713, 0.0936, 0.3176, 0.9246],
        [0.1478, 0.0356, 0.3905, 0.8292]])


In [29]:
print (tensor[1:3])

tensor([[0.2400, 0.3001, 0.4728, 0.2524],
        [0.5713, 0.0936, 0.3176, 0.9246]])


In [31]:
print (tensor[:2])

tensor([[0.6647, 0.7188, 0.3548, 0.8124],
        [0.2400, 0.3001, 0.4728, 0.2524]])


In [32]:
print (tensor[:-1])

tensor([[0.6647, 0.7188, 0.3548, 0.8124],
        [0.2400, 0.3001, 0.4728, 0.2524],
        [0.5713, 0.0936, 0.3176, 0.9246]])


In [33]:
print (tensor[1:4:2]) # Only 1 and 3rd rows 

tensor([[0.2400, 0.3001, 0.4728, 0.2524],
        [0.1478, 0.0356, 0.3905, 0.8292]])


In [34]:
print (tensor[1:4:2, :2]) # # Only 1 and 3rd rows and first two columns 

tensor([[0.2400, 0.3001],
        [0.1478, 0.0356]])


In [37]:
t1 = torch.cat([tensor, tensor], dim=1)
print (t1)

tensor([[0.6647, 0.7188, 0.3548, 0.8124, 0.6647, 0.7188, 0.3548, 0.8124],
        [0.2400, 0.3001, 0.4728, 0.2524, 0.2400, 0.3001, 0.4728, 0.2524],
        [0.5713, 0.0936, 0.3176, 0.9246, 0.5713, 0.0936, 0.3176, 0.9246],
        [0.1478, 0.0356, 0.3905, 0.8292, 0.1478, 0.0356, 0.3905, 0.8292]])


In [38]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

tensor.mul(tensor) 
 tensor([[0.4418, 0.5167, 0.1259, 0.6600],
        [0.0576, 0.0901, 0.2236, 0.0637],
        [0.3264, 0.0088, 0.1009, 0.8548],
        [0.0218, 0.0013, 0.1525, 0.6876]]) 



In [39]:
print (tensor**2)

tensor([[0.4418, 0.5167, 0.1259, 0.6600],
        [0.0576, 0.0901, 0.2236, 0.0637],
        [0.3264, 0.0088, 0.1009, 0.8548],
        [0.0218, 0.0013, 0.1525, 0.6876]])


In [41]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[1.7444, 0.7481, 1.3108, 0.9361],
        [0.7481, 0.4350, 0.5487, 0.4401],
        [1.3108, 0.5487, 1.2908, 0.9785],
        [0.9361, 0.4401, 0.9785, 0.8632]]) 

tensor @ tensor.T 
 tensor([[1.7444, 0.7481, 1.3108, 0.9361],
        [0.7481, 0.4350, 0.5487, 0.4401],
        [1.3108, 0.5487, 1.2908, 0.9785],
        [0.9361, 0.4401, 0.9785, 0.8632]])


In [46]:
tensor.add_(1)
print(tensor)

tensor([[1.6647, 1.7188, 1.3548, 1.8124],
        [1.2400, 1.3001, 1.4728, 1.2524],
        [1.5713, 1.0936, 1.3176, 1.9246],
        [1.1478, 1.0356, 1.3905, 1.8292]])


In [47]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [48]:
scalar.ndim

0

In [49]:
scalar.item()

7

In [52]:
torch.max(tensor), torch.min(tensor), torch.mean(tensor.type(torch.float32)), torch.sum(tensor)

(tensor(1.9246), tensor(1.0356), tensor(1.4454), tensor(23.1263))

In [53]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [56]:
# Create a tensor by reshaping list 

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Check http://www.learnpytorch.io/00_pytorch_fundamentals/ for more related stuff 